### ISSUE TITLE
"user.txt not found"

### ISSUE THREAD

**Issue by Akul2010** [jeffreyrdcs/RDPass-GUI#2]

**Comment by jeffreyrdcs** [comment]
Hi, I don't recall it needs a user.txt to work. Can you be a bit more specific?  Thanks!

**Comment by Akul2010** [comment]
when i run the program it says "user.txt not found" due to this I can't even open it

**Comment by Akul2010** [comment]
nvrm figured it out

**Comment by Akul2010** [comment]
great... now it says the following

ModuleNotFoundError: No module named 'bcrypt'

**Comment by Akul2010** [comment]
even after I type in pip install py-bcrypt separately

**Comment by jeffreyrdcs** [comment]
Did you install py-bcrypt successfully?  Otherwise it shouldn't give you the no module error.

**Comment by Akul2010** [comment]
it said something like this when I tried


Collecting py-bcrypt
  Using cached py-bcrypt-0.4.tar.gz (27 kB)
Using legacy 'setup.py install' for py-bcrypt, since package 'wheel' is not installed.
Installing collected packages: py-bcrypt
    Running setup.py install for py-bcrypt: started
    Running setup.py install for py-bcrypt: finished with status 'error'
pip :     ERROR: Command errored out with exit status 1:
At line:1 char:1
+ pip install py-bcrypt
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (    ERROR: Comm... exit status 1::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
     command: 'C:\Users\materialsworld\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = 
'"'"'C:\\Users\\materialsworld\\AppData\\Local\\Temp\\pip-install-l1bn33f3\\py-bcrypt_9c9772b7fa654f33a337cd967b861997\\setup.py'"'"'; 
__file__='"'"'C:\\Users\\materialsworld\\AppData\\Local\\Temp\\pip-install-l1bn33f3\\py-bcrypt_9c9772b7fa654f33a337cd967b861997\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if 
os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' 
install --record 'C:\Users\materialsworld\AppData\Local\Temp\pip-record-ly83slwc\install-record.txt' --single-version-externally-managed --compile --install-headers 
'C:\Users\materialsworld\AppData\Local\Programs\Python\Python39\Include\py-bcrypt'
         cwd: C:\Users\materialsworld\AppData\Local\Temp\pip-install-l1bn33f3\py-bcrypt_9c9772b7fa654f33a337cd967b861997\
    Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\bcrypt
    copying bcrypt\__init__.py -> build\lib.win-amd64-3.9\bcrypt
    running build_ext
    building 'bcrypt._bcrypt' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\materialsworld\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = 
'"'"'C:\\Users\\materialsworld\\AppData\\Local\\Temp\\pip-install-l1bn33f3\\py-bcrypt_9c9772b7fa654f33a337cd967b861997\\setup.py'"'"'; 
__file__='"'"'C:\\Users\\materialsworld\\AppData\\Local\\Temp\\pip-install-l1bn33f3\\py-bcrypt_9c9772b7fa654f33a337cd967b861997\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if 
os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' 
install --record 'C:\Users\materialsworld\AppData\Local\Temp\pip-record-ly83slwc\install-record.txt' --single-version-externally-managed --compile --install-headers 
'C:\Users\materialsworld\AppData\Local\Programs\Python\Python39\Include\py-bcrypt' Check the logs for full command output.


I'm not sure why this keeps happening

**Comment by Akul2010** [comment]
it gave an error like there is any proper version, so it can't download

what is that supposed to mean

**Comment by jeffreyrdcs** [comment]
That means it is not installed correctly.  Which OS / python are you using?  If 3.9 doesn't work you could try a lower version, but it shouldn't give you a problem.
Another problem might be missing wheels or dependencies, especially if you are using windows.
