### ISSUE TITLE
Problem when adding entry

### ISSUE THREAD

**Issue by Akul2010** [jeffreyrdcs/RDPass-GUI#5]
When I try to add a new entry, it give the following error:

   File "c:\Users\materialsworld\Desktop\RDPass-GUI-master\rdpass.kv", line 868, in <module>
     on_press:  root.confirmbutton_onpress()
     new_entry = CredEntry(title=self.ids.titl_simpfield.text,
     self.password = encrypt_pass(password.encode(), self.salt.encode())
 AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?

After giving this error the application closes. How do I fix this? Thank you.

**Comment by jeffreyrdcs** [comment]
Hi, I think this is the same error as issue #1 . I would suggest to first check if the correct packages are installed.

Here's my response in issue #1 :

> Judging from the last line "AttributeError: 'bytes' object has no attribute 'encode'", I think you may be using the package "bcrypt" where the code requires "py-bcrypt". The two packages have similar function and module name, but one give a byte output the other gives a string output, which causes the error. If this is true, to fix it you may have to uninstall bcrypt, then install py-bcrypt.   The package I used is listed in requirements.txt.

**Comment by Akul2010** [comment]
I can't install py-bcrypt, it gives me following error:

C:\Users\materialsworld>pip install py-bcrypt
Collecting py-bcrypt
  Using cached py-bcrypt-0.4.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: py-bcrypt
  Building wheel for py-bcrypt (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\bcrypt
      copying bcrypt\__init__.py -> build\lib.win-amd64-3.10\bcrypt
      running build_ext
      building 'bcrypt._bcrypt' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py-bcrypt
  Running setup.py clean for py-bcrypt
Failed to build py-bcrypt
Installing collected packages: py-bcrypt
  Running setup.py install for py-bcrypt ... error
  error: subprocess-exited-with-error

  × Running setup.py install for py-bcrypt did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\bcrypt
      copying bcrypt\__init__.py -> build\lib.win-amd64-3.10\bcrypt
      running build_ext
      building 'bcrypt._bcrypt' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> py-bcrypt

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Akul2010** [comment]
I have py-bcrypt, but now it is giving me this error when trying to log in to database:

File "c:\Users\materialsworld\Desktop\RDPass-GUI-master\RDutils\rdencrypt.py", line 22, in validate_hashed_key
     return bcrypt.checkpw(input_pw_to_check.encode('utf8'), hashed_key.encode('utf8'))
 AttributeError: module 'bcrypt' has no attribute 'checkpw'

**Comment by jeffreyrdcs** [comment]
Umm I am not sure why that happens. Maybe make sure you have uninstalled bcrypt, so you are not still importing the wrong library? You can check that with `pip list` if you are using pip. I just checked with a fresh conda environment with python 3.8.  And it works without any issue after installing the dependencies in requirement.txt.

**Comment by Akul2010** [comment]
I have uninstalled bcrypt, and install py-bcrypt, and that's the error it gave me. It seems that py-bcrypt doesn't have the checkpw function mentioned in the code.

**Comment by jeffreyrdcs** [comment]
That's weird, since the py-bcrypt library definitely has the function, may be it was not installed correctly. I have a suggestion, could you try to run the following in a separate file?

```
import bcrypt

password = b'secretpassword'

salt = '$2a$12$PHjxFy12BhFLuEX0nZfk6.'""
hashed_password = bcrypt.hashpw(passwd, salt)

if bcrypt.checkpw(password, hashed_password):
    print("password match!")
else:
    print("password does not match!")
```

If the above does not work, it is likely that your py-bcrypt was not installed correctly.

**Comment by Akul2010** [comment]
It still gives the same error; py-bcrypt definitely must be installed incorrectly. How do I install it correctly?

**Comment by jeffreyrdcs** [comment]
That depends on what you are using to install it.  Are you using pip, or vitual env like conda?

**Comment by Akul2010** [comment]
I am using pip.

**Comment by jeffreyrdcs** [comment]
Was there any error message? Hard to believe that a pip install would fail only for a certain part of the library.
